"""
agents/render_agent.py
======================
Subagent responsible for composing the final PDF report using ReportLab's
Platypus framework (document-flow engine).

The PDF contains:
  1. Title page / header with generation timestamp
  2. Executive summary (grand total, date range, category count)
  3. Per-category detail table (description, date, amount)
  4. Category summary table (total, count, avg, share %)
  5. Pie chart (generated by ChartAgent)
  6. Metrics appendix

Input  : ExpenseReport + chart_path (PNG)
Output : Path to the final PDF
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Optional

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import (
    HRFlowable,
    Image,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from agents.base import BaseAgent, ValidationResult, ValidationStatus
from core.models import ExpenseReport

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Design tokens
# ---------------------------------------------------------------------------
BRAND_BLUE   = colors.HexColor("#2E86AB")
BRAND_DARK   = colors.HexColor("#1A1A2E")
ACCENT_GREEN = colors.HexColor("#27AE60")
TABLE_HEADER = colors.HexColor("#2E86AB")
ROW_ALT      = colors.HexColor("#F4F7FA")
ROW_WHITE    = colors.white
TEXT_DARK    = colors.HexColor("#2C2C2C")

PAGE_W, PAGE_H = A4
MARGIN = 2.0 * cm


@dataclass
class RenderInput:
    """Input contract for the RenderAgent."""
    report: ExpenseReport
    chart_path: Optional[Path] = None


@dataclass
class RenderConfig:
    output_path: Path
    author: str = "Expense Tracker"
    subject: str = "Relatório de Despesas"
    logo_path: Optional[Path] = None


class RenderAgent(BaseAgent[RenderInput, Path]):
    """
    Composes and writes the final PDF report.

    Inherits timing, logging and error handling from ``BaseAgent``.
    Uses ReportLab Platypus (document-flow / stylesheet system) rather
    than the low-level canvas API so that page breaks, text reflow and
    table pagination are handled automatically.
    """

    name = "RenderAgent"

    def __init__(self, config: RenderConfig) -> None:
        super().__init__()
        self.config = config

    def validate(self) -> ValidationResult:
        result = ValidationResult()
        out = self.config.output_path
        try:
            out.parent.mkdir(parents=True, exist_ok=True)
        except OSError as e:
            result.add_error(f"Cannot create output directory '{out.parent}': {e}")
            return result
        if out.exists() and not out.is_file():
            result.add_error(f"Output path '{out}' exists but is not a file")
        return result

    def _execute(self, inp: RenderInput) -> Path:
        """Compose and write the PDF; return the output path."""
        return self._render(inp.report, inp.chart_path)

    def _render(self, report: ExpenseReport, chart_path: Optional[Path] = None) -> Path:
        """Internal rendering logic — separated so it can be called directly in tests."""
        cfg = self.config
        styles = self._build_styles()

        doc = SimpleDocTemplate(
            str(cfg.output_path),
            pagesize=A4,
            leftMargin=MARGIN,
            rightMargin=MARGIN,
            topMargin=MARGIN,
            bottomMargin=MARGIN,
            title="Relatório de Despesas",
            author=cfg.author,
            subject=cfg.subject,
        )

        story = []
        story += self._build_header(report, styles)
        story += self._build_summary_section(report, styles)
        story += self._build_detail_table(report, styles)
        story += self._build_category_table(report, styles)
        if chart_path and chart_path.exists():
            story += self._build_chart_section(chart_path, styles)
        story += self._build_metrics_section(report, styles)

        doc.build(story, onFirstPage=self._header_footer, onLaterPages=self._header_footer)
        logger.info("[%s] PDF written to %s", self.name, cfg.output_path)
        return cfg.output_path

    # ------------------------------------------------------------------
    # Page header/footer (canvas-level callback)
    # ------------------------------------------------------------------

    def _header_footer(self, canvas, doc):
        canvas.saveState()
        # Top thin bar
        canvas.setFillColor(BRAND_BLUE)
        canvas.rect(0, PAGE_H - 0.6 * cm, PAGE_W, 0.6 * cm, fill=1, stroke=0)
        # Footer
        canvas.setFillColor(TEXT_DARK)
        canvas.setFont("Helvetica", 7)
        canvas.drawString(MARGIN, 0.8 * cm, "Expense Tracker — Relatório Confidencial")
        canvas.drawRightString(
            PAGE_W - MARGIN, 0.8 * cm, f"Página {doc.page}"
        )
        canvas.restoreState()

    # ------------------------------------------------------------------
    # Section builders
    # ------------------------------------------------------------------

    def _build_header(self, report: ExpenseReport, styles) -> list:
        items = []
        items.append(Spacer(1, 0.4 * cm))
        items.append(Paragraph("Relatório de Despesas", styles["ReportTitle"]))
        items.append(Spacer(1, 0.2 * cm))

        gen_at = report.generated_at.strftime("%d/%m/%Y às %H:%M")
        items.append(Paragraph(f"Gerado em {gen_at}", styles["SubTitle"]))
        if report.period_start and report.period_end:
            period = (
                f"Período: {report.period_start.strftime('%d/%m/%Y')} "
                f"→ {report.period_end.strftime('%d/%m/%Y')}"
            )
            items.append(Paragraph(period, styles["SubTitle"]))

        items.append(Spacer(1, 0.4 * cm))
        items.append(HRFlowable(width="100%", thickness=2, color=BRAND_BLUE))
        items.append(Spacer(1, 0.4 * cm))
        return items

    def _build_summary_section(self, report: ExpenseReport, styles) -> list:
        items = []
        items.append(Paragraph("Resumo Executivo", styles["SectionHeading"]))
        items.append(Spacer(1, 0.2 * cm))

        m = report.metrics
        kpis = [
            ["Total de despesas", str(report.grand_total)],
            ["Nº de registros", str(len(report.expenses))],
            ["Categorias", str(len(report.summaries))],
        ]
        if m:
            kpis += [
                ["Qualidade dos dados", f"{m.data_quality_pct:.1f}%"],
                ["Maior despesa", f"R$ {m.largest_single_expense:,.2f}"],
                ["Menor despesa", f"R$ {m.smallest_single_expense:,.2f}"],
                ["Desvio padrão", f"R$ {m.std_deviation:,.2f}"],
            ]

        # Two-column KPI grid
        rows_per_col = (len(kpis) + 1) // 2
        col_a = kpis[:rows_per_col]
        col_b = kpis[rows_per_col:]
        while len(col_b) < len(col_a):
            col_b.append(["", ""])

        table_data = []
        for (k1, v1), (k2, v2) in zip(col_a, col_b):
            table_data.append([k1, v1, k2, v2])

        col_w = (PAGE_W - 2 * MARGIN) / 4
        kpi_table = Table(table_data, colWidths=[col_w * 1.4, col_w * 0.6, col_w * 1.4, col_w * 0.6])
        kpi_table.setStyle(TableStyle([
            ("FONTNAME",    (0, 0), (-1, -1), "Helvetica"),
            ("FONTSIZE",    (0, 0), (-1, -1), 9),
            ("FONTNAME",    (1, 0), (1, -1), "Helvetica-Bold"),
            ("FONTNAME",    (3, 0), (3, -1), "Helvetica-Bold"),
            ("TEXTCOLOR",   (1, 0), (1, -1), BRAND_BLUE),
            ("TEXTCOLOR",   (3, 0), (3, -1), BRAND_BLUE),
            ("FONTSIZE",    (1, 0), (1, -1), 10),
            ("FONTSIZE",    (3, 0), (3, -1), 10),
            ("ROWBACKGROUNDS", (0, 0), (-1, -1), [ROW_WHITE, ROW_ALT]),
            ("TOPPADDING",  (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING",(0, 0), (-1, -1), 5),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ]))
        items.append(kpi_table)
        items.append(Spacer(1, 0.5 * cm))
        return items

    def _build_detail_table(self, report: ExpenseReport, styles) -> list:
        items = []
        items.append(Paragraph("Detalhamento por Despesa", styles["SectionHeading"]))
        items.append(Spacer(1, 0.2 * cm))

        header = ["#", "Descrição", "Categoria", "Data", "Valor"]
        rows = [header]
        # Sort by category then date
        sorted_exp = sorted(
            report.expenses,
            key=lambda e: (e.category.name, e.expense_date)
        )
        for i, e in enumerate(sorted_exp, 1):
            rows.append([
                str(i),
                e.description[:45] + ("…" if len(e.description) > 45 else ""),
                e.category.name,
                e.expense_date.strftime("%d/%m/%Y"),
                str(e.amount),
            ])

        available_w = PAGE_W - 2 * MARGIN
        col_widths = [
            available_w * 0.05,
            available_w * 0.38,
            available_w * 0.22,
            available_w * 0.15,
            available_w * 0.20,
        ]
        table = Table(rows, colWidths=col_widths, repeatRows=1)
        table.setStyle(self._detail_table_style())
        items.append(table)
        items.append(Spacer(1, 0.5 * cm))
        return items

    def _build_category_table(self, report: ExpenseReport, styles) -> list:
        items = []
        items.append(Paragraph("Resumo por Categoria", styles["SectionHeading"]))
        items.append(Spacer(1, 0.2 * cm))

        header = ["Categoria", "Registros", "Total", "Média", "% do Total"]
        rows = [header]
        for s in report.summaries:
            rows.append([
                s.category_name,
                str(s.count),
                str(s.total),
                str(s.average),
                f"{s.percentage:.1f}%",
            ])
        # Grand total row
        rows.append([
            "TOTAL",
            str(len(report.expenses)),
            str(report.grand_total),
            "",
            "100%",
        ])

        available_w = PAGE_W - 2 * MARGIN
        col_widths = [
            available_w * 0.30,
            available_w * 0.12,
            available_w * 0.22,
            available_w * 0.22,
            available_w * 0.14,
        ]
        table = Table(rows, colWidths=col_widths, repeatRows=1)
        table.setStyle(self._summary_table_style(len(rows)))
        items.append(table)
        items.append(Spacer(1, 0.5 * cm))
        return items

    def _build_chart_section(self, chart_path: Path, styles) -> list:
        items = []
        items.append(PageBreak())
        items.append(Paragraph("Distribuição Visual por Categoria", styles["SectionHeading"]))
        items.append(Spacer(1, 0.3 * cm))

        available_w = PAGE_W - 2 * MARGIN
        img = Image(str(chart_path), width=available_w, height=available_w * 0.65)
        items.append(img)
        items.append(Spacer(1, 0.3 * cm))
        return items

    def _build_metrics_section(self, report: ExpenseReport, styles) -> list:
        if not report.metrics:
            return []
        items = []
        items.append(Spacer(1, 0.2 * cm))
        items.append(HRFlowable(width="100%", thickness=1, color=colors.lightgrey))
        items.append(Spacer(1, 0.2 * cm))
        items.append(Paragraph("Métricas de Processamento", styles["SectionHeading"]))
        items.append(Spacer(1, 0.2 * cm))

        m = report.metrics
        metric_rows = [
            ["Registros lidos", str(m.total_records_read),
             "Registros válidos", str(m.valid_records)],
            ["Registros inválidos", str(m.invalid_records),
             "Duplicatas ignoradas", str(m.duplicate_records)],
            ["Qualidade dos dados", f"{m.data_quality_pct:.1f}%",
             "Tempo de parse", f"{m.parse_duration_s:.3f}s"],
            ["Tempo de agregação", f"{m.aggregation_duration_s:.3f}s",
             "Tempo de renderização", f"{m.render_duration_s:.3f}s"],
            ["Tempo total", f"{m.total_duration_s:.3f}s",
             "Intervalo (dias)", str(m.date_range_days)],
        ]

        available_w = PAGE_W - 2 * MARGIN
        col_w = available_w / 4
        tbl = Table(metric_rows, colWidths=[col_w * 1.3, col_w * 0.7, col_w * 1.3, col_w * 0.7])
        tbl.setStyle(TableStyle([
            ("FONTNAME",    (0, 0), (-1, -1), "Helvetica"),
            ("FONTSIZE",    (0, 0), (-1, -1), 8),
            ("FONTNAME",    (1, 0), (1, -1), "Helvetica-Bold"),
            ("FONTNAME",    (3, 0), (3, -1), "Helvetica-Bold"),
            ("TEXTCOLOR",   (1, 0), (1, -1), ACCENT_GREEN),
            ("TEXTCOLOR",   (3, 0), (3, -1), ACCENT_GREEN),
            ("ROWBACKGROUNDS", (0, 0), (-1, -1), [ROW_WHITE, ROW_ALT]),
            ("TOPPADDING",  (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING",(0, 0), (-1, -1), 4),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ]))
        items.append(tbl)
        return items

    # ------------------------------------------------------------------
    # Table styles
    # ------------------------------------------------------------------

    @staticmethod
    def _detail_table_style() -> TableStyle:
        return TableStyle([
            # Header
            ("BACKGROUND",   (0, 0), (-1, 0), TABLE_HEADER),
            ("TEXTCOLOR",    (0, 0), (-1, 0), colors.white),
            ("FONTNAME",     (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE",     (0, 0), (-1, 0), 9),
            ("ALIGN",        (0, 0), (-1, 0), "CENTER"),
            # Body
            ("FONTNAME",     (0, 1), (-1, -1), "Helvetica"),
            ("FONTSIZE",     (0, 1), (-1, -1), 8),
            ("ROWBACKGROUNDS",(0, 1), (-1, -1), [ROW_WHITE, ROW_ALT]),
            ("ALIGN",        (0, 1), (0, -1), "CENTER"),
            ("ALIGN",        (4, 1), (4, -1), "RIGHT"),
            ("TOPPADDING",   (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING",(0, 0), (-1, -1), 4),
            ("LEFTPADDING",  (0, 0), (-1, -1), 5),
            ("GRID",         (0, 0), (-1, -1), 0.3, colors.HexColor("#DDDDDD")),
        ])

    @staticmethod
    def _summary_table_style(n_rows: int) -> TableStyle:
        last = n_rows - 1
        return TableStyle([
            # Header
            ("BACKGROUND",   (0, 0), (-1, 0), TABLE_HEADER),
            ("TEXTCOLOR",    (0, 0), (-1, 0), colors.white),
            ("FONTNAME",     (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE",     (0, 0), (-1, 0), 9),
            ("ALIGN",        (0, 0), (-1, 0), "CENTER"),
            # Body
            ("FONTNAME",     (0, 1), (-1, last-1), "Helvetica"),
            ("FONTSIZE",     (0, 1), (-1, last-1), 9),
            ("ROWBACKGROUNDS",(0, 1), (-1, last-1), [ROW_WHITE, ROW_ALT]),
            ("ALIGN",        (1, 1), (-1, -1), "RIGHT"),
            # Total row
            ("BACKGROUND",   (0, last), (-1, last), BRAND_DARK),
            ("TEXTCOLOR",    (0, last), (-1, last), colors.white),
            ("FONTNAME",     (0, last), (-1, last), "Helvetica-Bold"),
            ("FONTSIZE",     (0, last), (-1, last), 9),
            ("TOPPADDING",   (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING",(0, 0), (-1, -1), 5),
            ("LEFTPADDING",  (0, 0), (-1, -1), 6),
            ("GRID",         (0, 0), (-1, -1), 0.3, colors.HexColor("#DDDDDD")),
        ])

    # ------------------------------------------------------------------
    # Style sheet
    # ------------------------------------------------------------------

    @staticmethod
    def _build_styles() -> dict:
        base = getSampleStyleSheet()
        custom = {}

        custom["ReportTitle"] = ParagraphStyle(
            "ReportTitle",
            parent=base["Title"],
            fontSize=22,
            textColor=BRAND_DARK,
            spaceAfter=4,
            alignment=TA_CENTER,
            fontName="Helvetica-Bold",
        )
        custom["SubTitle"] = ParagraphStyle(
            "SubTitle",
            parent=base["Normal"],
            fontSize=9,
            textColor=colors.HexColor("#555555"),
            alignment=TA_CENTER,
            spaceAfter=2,
        )
        custom["SectionHeading"] = ParagraphStyle(
            "SectionHeading",
            parent=base["Heading2"],
            fontSize=12,
            textColor=BRAND_BLUE,
            spaceBefore=8,
            spaceAfter=4,
            fontName="Helvetica-Bold",
            borderPad=0,
        )
        return custom